# Generated by Django 3.0 on 2019-12-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.IntegerField(default=11000),
            preserve_default=False,
        ),
    ]
